USE bakery;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Leaves;
DROP TABLE IF EXISTS Attendance;
DROP TABLE IF EXISTS Salaries;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Jobs;
DROP TABLE IF EXISTS Departments;

SET FOREIGN_KEY_CHECKS = 1;